#!/bin/bash

cd "/Applications/CrackAssistant.app/"

# process origin binary
mv CrackAssistant CrackAssistant_
chown root.wheel CrackAssistant_
chmod +s CrackAssistant_

cont=`cat <<"EOF"
#!/bin/bash
dir=$(dirname "$0")
exec "${dir}"/CrackAssistant_ "$@"
EOF
`
# create new fake binary
echo -e "$cont" > CrackAssistant
chown root.wheel  CrackAssistant
chmod +x CrackAssistant
